---
management:
  port: 8081
  context-path: /management
  endpoints:
    health:
      enabled: true    
  security:
    enabled: true

security:
  user:
    name: qx
    password: qx

---
app: 
  jwt.secret: secret
  username: test
  password: test
  expiration: 1440
  tenants:
    -
      tenantId: intraway.ar.qoe
      url: jdbc:mysql://localhost:3306/intraway.ar.qoe?zeroDateTimeBehavior=convertToNull
      username: bmonitor
      password: iwjaja
      driverClassName: com.mysql.jdbc.Driver
      maxActive: 10
      maxIdle: 1
      validationQuery: select 1
      maxAge: 300000      
    -
      tenantId: vtr.cl.qoe
      url: jdbc:mysql://localhost:3306/vtr.cl.qoe?zeroDateTimeBehavior=convertToNull
      username: bmonitor
      password: iwjaja
      driverClassName: com.mysql.jdbc.Driver
      maxActive: 10
      maxIdle: 1
      validationQuery: select 1
      maxAge: 300000      

---
server:
    port: 9991
    compression:
      enabled: true 

---
logging:
  level:
    com.intraway.qx: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR