---
app:
  countryInformationUrl: http://restcountries.eu/rest/v1/alpha/ 
  ip2CountryUrl: https://api.ip2country.info/ip?
  priceUrl: http://api.fixer.io/latest?base=

---
server:
    port: 9991
    compression:
      enabled: true 

